---

  master_node: true
  role_separation: false
  hostgroup: default
  configure_cluster: false
  oracle_psu_apply_db: true

  oracle_user: oracle                        # User that will own the Oracle Installations.
  oracle_user_home: "/home/{{ oracle_user }}" # Home directory for oracle_user. Needed for passing in ssh-keys, profiles etc
  oracle_group: oinstall                          # Primary group for oracle_user. 

  oracle_sw_source_www: http://www/orasw     # address to all software if using the get_url module when putting software on the host(s)
  oracle_sw_source_local: /tmp  # Path to all software if using the copy module when putting software on the host(s)
  is_sw_source_local: true
  install_from_nfs: false
  oracle_sw_copy: "{% if install_from_nfs==True %}False{% else %}True{% endif %}"
  oracle_sw_unpack: "{% if install_from_nfs==True %}False{% else %}True{% endif %}"
  nfs_server_sw: nfsserver
  nfs_server_sw_path: /path/to/orasw

  patchpath: "{% if item is defined and item.subpath is defined and item.version is defined %}{{ oracle_stage_install }}/{{ item.version }}/{{ item.subpath }}/{{ item.patchid }}{% endif %}"

  oracle_opatch_patch:
       - { filename: p6880880_122010_Linux-x86-64.zip, version: 12.2.0.1 }
       - { filename: p6880880_122010_Linux-x86-64.zip, version: 12.1.0.2 } # 12.1.0.2 uses OPatch from 12.2.0.1!
       - { filename: p6880880_121010_Linux-x86-64.zip, version: 12.1.0.1 }
       - { filename: p6880880_112000_Linux-x86-64.zip, version: 11.2.0.4 }
       - { filename: p6880880_112000_Linux-x86-64.zip, version: 11.2.0.3 }

  oracle_stage: /u01/stage
  oracle_stage_remote: "{{ oracle_stage }}"
  oracle_stage_install: "{% if oracle_sw_copy==False and oracle_sw_unpack==False%}{{ oracle_stage_remote }}{% else %}{{ oracle_stage }}{% endif %}"
  oracle_base: /u01/app/oracle

  oracle_home_db: "{% if item.0 is defined %}{% if item.0.oracle_home is defined %}{{ item.0.oracle_home}}{% else %}{{ oracle_base }}/{{ item.0.oracle_version_db }}/{{ item.0.home }}{% endif %}{% endif %}"

  opatcharchive: "{% if item.0 is defined %}{{ oracle_stage_install }}/{{ item.0.oracle_version_db }}/{% for opatchfile in oracle_opatch_patch if  opatchfile['version']==item.0.oracle_version_db%}{{ opatchfile['filename'] }}{% endfor %}{% endif %}"

  oracle_rsp_stage: "{{ oracle_stage }}/rsp"
  oracle_psu_stage: "{{ oracle_stage }}/psu"

  ocmrfparam: "{% if '11.2' in item.version %} -ocmrf {{item.path}}/OPatch/ocm.rsp {% endif %}"

  oracle_hostname: "{{ ansible_fqdn }}"                            # Full (FQDN) name of the host

#   oracle_patch_list:
#      - desc: "PSU 12.1.0.2.180117"
#        patchid: 26925311
#        subpath: 27010888/27010888/27010872
#        version: 12.1.0.2
#        opatchauto: False
#        ORACLE_HOME:
#           - path: /u01/app/oracle/12.1.0.2/myhomeasm
#             apply: True
#
#      - desc: "Database PSU 12.1.0.2.180116, Oracle JavaVM Component"
#        patchid: 27001733
#        subpath: 27010888/27010888
#        version: 12.1.0.2
#        opatchauto: False
#        ORACLE_HOME:
#           - path: /u01/app/oracle/12.1.0.2/myhomeasm
#             apply: True
#
#      - desc: "OCW Patch Set Update : 12.1.0.2.180116"
#        patchid: 26925218
#        subpath: 27010888/27010888/27010872
#        version: 12.1.0.2
#        opatchauto: False
#        ORACLE_HOME:
#           - path: /u01/app/oracle/12.1.0.2/myhomeasm
#             apply: True
#
